import SwiftUI

// MARK: - Colors

extension Color {
    // Zone accents
    static let zoneRecovery = Color(hex: "#4A9EDB")
    static let zoneBase = Color(hex: "#3FB87F")
    static let zoneThreshold = Color(hex: "#E8A94C")
    static let zoneInterval = Color(hex: "#E35D5D")
    static let zoneRest = Color(hex: "#8A8F99")
    static let zoneLong = Color(hex: "#8F7BD4")

    // Brand
    static let rcAccent = Color(hex: "#3FB87F")

    init(hex: String) {
        let hex = hex.trimmingCharacters(in: CharacterSet.alphanumerics.inverted)
        var int: UInt64 = 0
        Scanner(string: hex).scanHexInt64(&int)
        let r = Double((int >> 16) & 0xFF) / 255
        let g = Double((int >> 8) & 0xFF) / 255
        let b = Double(int & 0xFF) / 255
        self.init(red: r, green: g, blue: b)
    }
}

extension ZoneColor {
    var color: Color {
        switch self {
        case .recovery: .zoneRecovery
        case .base: .zoneBase
        case .threshold: .zoneThreshold
        case .interval: .zoneInterval
        case .rest: .zoneRest
        case .long: .zoneLong
        }
    }

    var label: String {
        switch self {
        case .recovery: "회복"
        case .base: "기본"
        case .threshold: "역치"
        case .interval: "인터벌"
        case .rest: "휴식"
        case .long: "장거리"
        }
    }
}

// ShapeStyle extensions for hex-based colors (asset catalog colors are auto-generated by Xcode)
extension ShapeStyle where Self == Color {
    static var rcAccent: Color { Color(hex: "#3FB87F") }
    static var zoneRecovery: Color { Color(hex: "#4A9EDB") }
    static var zoneBase: Color { Color(hex: "#3FB87F") }
    static var zoneThreshold: Color { Color(hex: "#E8A94C") }
    static var zoneInterval: Color { Color(hex: "#E35D5D") }
    static var zoneRest: Color { Color(hex: "#8A8F99") }
    static var zoneLong: Color { Color(hex: "#8F7BD4") }
}

// MARK: - Typography

extension Font {
    static func rcTitle(_ size: CGFloat = 34) -> Font {
        .custom("PretendardVariable", size: size).weight(.bold)
    }

    static func rcHeadline(_ size: CGFloat = 17) -> Font {
        .custom("PretendardVariable", size: size).weight(.semibold)
    }

    static func rcBody(_ size: CGFloat = 15) -> Font {
        .custom("PretendardVariable", size: size)
    }

    static func rcCaption(_ size: CGFloat = 12) -> Font {
        .custom("PretendardVariable", size: size)
    }

    static func rcMono(_ size: CGFloat = 15) -> Font {
        .custom("JetBrainsMono[wght]", size: size)
    }
}

// MARK: - Spacing

enum Spacing {
    static let xs: CGFloat = 4
    static let sm: CGFloat = 8
    static let md: CGFloat = 16
    static let lg: CGFloat = 24
    static let xl: CGFloat = 32
    static let xxl: CGFloat = 48
}

// MARK: - Corner Radius

enum Radius {
    static let sm: CGFloat = 8
    static let md: CGFloat = 16
    static let lg: CGFloat = 20
    static let xl: CGFloat = 28
    static let pill: CGFloat = 100
}
